### ISSUE TITLE
Example usage?

### ISSUE THREAD

**Issue by michaeljones** [karen-irc/option-t#1213]
I've been looking around the repository for 5-10 minutes and I can't see any examples of what code with this approach generally looks like? In particular I'm not sure what the approach for importing is. It looks like all functions are individually imported rather than being accessible from a single imported namespace or something? 

I realise this can be good for tree shaking so it is perfectly understandable. I would just feel more confident setting off on using this package if there were a few examples of what it generally ends up looking like?

I'm sorry if this is an inappropriate use of an issue or if there are already examples and I've just failed to find them. It looks like an impressive project! And it is exciting to see something that takes inspiration from the Rust APIs as I also like coding in Rust.

**Comment by tetsuharuohzeki** [comment]
@michaeljones 

I'm apologize to this reply was late.
I'll answer to your questions...

----

> I've been looking around the repository for 5-10 minutes and I can't see any examples of what code with this approach generally looks like? In particular I'm not sure what the approach for importing is. It looks like all functions are individually imported rather than being accessible from a single imported namespace or something?
>
> I realise this can be good for tree shaking so it is perfectly understandable. I would just feel more confident setting off on using this package if there were a few examples of what it generally ends up looking like?

1. At this moment, our best examples are [test codes under `__tests__/`](https://github.com/karen-irc/option-t/tree/main/__tests__).
    - Path which you can import are listed in https://github.com/karen-irc/option-t/blob/main/docs/public_api_list.md and its document have links to each of actual implementations.
    - We don't provide a single namespace because it would be problematic about bundled code size in commonjs case with legacy bundlers, and I think it's not clear that providing multiple features into single namespace. So you can import some namespace listed up in [this section](https://github.com/karen-irc/option-t#utility-functions-for-some-types). For example, `Nullable`, [option-t/Nullable] provides [these functions](https://github.com/karen-irc/option-t/blob/main/src/Nullable/index.ts) and you can use just `import * as Nullable from 'option-t/Nullable';`.
1. And sorry, we don't have a nice example to combine some operator functions. Historically, this project grows up to use with my internal/private application. We don't have a much example to illustrate some common pattern open source codes with using this project. 
    - This also has an aspect which is simply choice to escape from the effort to maintain documentations. Instead, this project use similar APIs names to Rust's original ones to reduce the recognization and mental model gaps.


----

> I'm sorry if this is an inappropriate use of an issue or if there are already examples and I've just failed to find them. It looks like an impressive project! And it is exciting to see something that takes inspiration from the Rust APIs as I also like coding in Rust.

Don't worry! Thank you for that you're interested in this project!

**Comment by tetsuharuohzeki** [comment]
I close this issue as no active. Feel free to reopen if you need to continue the discussion of this topic.

**Comment by michaeljones** [comment]
I'm sorry for having left this hanging. I appreciate your reply. It helped me to evaluate the package. I should have closed it down afterwards though. Thanks for the help.

**Comment by tetsuharuohzeki** [comment]
You're welcome! If you have an another question, please file a new issue or open a new discussion :)
