### ISSUE TITLE
Does this support deserialization ( IE use Option types for an API )?

### ISSUE THREAD

**Issue by dessalines** [karen-irc/option-t#1302]
I'd like to use these Option types in an API, IE currently an interface might be:

```ts
interface Person {
  name: string;
  display_name?: string // I'd like this to be display_name: Option<string>;
  ...
}
```

**Comment by tetsuharuohzeki** [comment]
@dessalines 

>  Does this support deserialization ( IE use Option types for an API )?

Yes. [`PlainResult`](https://github.com/karen-irc/option-t/blob/075ffb7b23d73f67622208714adfd24c2ae2b42a/src/PlainResult/Result.ts) &  [`PlainOption`](https://github.com/karen-irc/option-t/blob/075ffb7b23d73f67622208714adfd24c2ae2b42a/src/PlainOption/Option.ts) will be JSON directly.

For deprecated API, we need to be careful:

- [`ClassicOption` has `toJSON`](https://github.com/karen-irc/option-t/blob/075ffb7b23d73f67622208714adfd24c2ae2b42a/src/ClassOption/ClassicOption.js#L269-L275)
- [`ClassicResult`](https://github.com/karen-irc/option-t/blob/075ffb7b23d73f67622208714adfd24c2ae2b42a/src/ClassResult/ClassicResult.js#L22-L39) does not support it (and we will not add the support). So it will expose the internal structure directly if you do` JSON.stringfiy(classicResultInstance)`.

-----

If you would like to use other JSON serialization, you can write custom `toJSON()` to your objects:

> If the value has a [toJSON()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior) method, it's responsible to define what data will be serialized.
>
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

**Comment by dessalines** [comment]
Okay thank you!
