### ISSUE TITLE
Emit ES6 or later code

### ISSUE THREAD

**Issue by tetsuharuohzeki** [karen-irc/option-t#382]
## Motivation

* Now, we keep to emit es5 to support IE11.
    * But Windows 7 will be EoL January 14, 2020.
* We don't mind to use ES5 as final syntax.
    * Supporting IE11 is key point.

## TODO

- [ ] How migration if user projects suppprt IE11.
- [ ] What is the best ES version to jump?

## Related Issues

- Block?: https://github.com/karen-irc/option-t/issues/306
- Block?: https://github.com/karen-irc/option-t/issues/305

**Comment by saneyuki** [comment]
At first, we should wait https://github.com/karen-irc/option-t/issues/421

**Comment by saneyuki** [comment]
We don't have strong motivation to emit ES6 or later code because we can implement our primary features with ES5 syntax.

We should move to ES6 or later if there are magical speedup chance. But I don't seem there is such room.

**Comment by tetsuharuohzeki** [comment]
Dup with #1236
