### ISSUE TITLE
Passing PlainOption to operator assuming to accept PlainResult might cause loose typing

### ISSUE THREAD

**Issue by tetsuharuohzeki** [karen-irc/option-t#387]
## Motivation

The following code would be valid.

```typescript
import { createSome, Option } from 'option-t/esm/PlainOption/Option';
import { unwrapErrFromResult } from 'option-t/esm/PlainResult/unwrap';

const a: Option<number> = createNone();

// With typescript 3.5, this b would be `unknown`.
// With typescript ~3.4, this b would be `{}`
const b = unwrapErrFromResult(a); 
```

This behavior is convenient, but I suspect this would be a bit problem for users.

1. If user misuse a code, then the return value would change tricky type.
    - TypeScript 3.5~, this _b_ will be `unknown` type. This is a bit safe.
    - But TypeScript ~3.4, this _b_ will be `{}`. This is horrible.
    - TypeScript's semantics sometimes change. We should provide a more coherent way which is free from TypeScript semantics' corner case .
1. I'd like to ban this kind of misusing via compile phase aggressively.

So I'd like to fix it.

## Proposed Design

Add _unique symbol_ type member to both of `PlainOption::Option` and `PlainResult::Result`.

As like a Phantom Type. I think it's better that `createSome()` or others don't add this type actually on the runtime for perf and backward compatibility with legacy UAs.

* https://doc.rust-lang.org/rust-by-example/generics/phantom.html
* https://doc.rust-lang.org/std/marker/struct.PhantomData.html
* https://wiki.haskell.org/Phantom_type

```typescript
declare const marker: unique symbol;

export declare type Option<T> = Some<T> | None;

export declare type Some<T> = {
    readonly ok: true;
    readonly val: T;
     readonly [marker]: unique symbol;
};

export declare type None = {
    readonly ok: false;
    readonly val?: undefined;
    readonly [marker]: unique symbol;
};
```

### 1. Need a breaking change.

* This might cause a compile error if user project pass `Option<T>` to operators
* I think we can detect it by typescript's compile error. I seem it would not be a serious problem.

### 2. Abandon the type coherency between `Ok<T>` and `Some<T>`

* This might fail an ergonomics.
* But we begun to abandon to it from https://github.com/karen-irc/option-t/pull/231.
* Now, we have `PlainResult::toOption()` and `PlainResult::okOrElse()`. We can convert them mutually.

**Comment by saneyuki** [comment]
The patch is [here](https://github.com/karen-irc/option-t/pull/388)

**Comment by saneyuki** [comment]
If there are multiple versions of this package in user dependency tree, this change may reproduce the similar problem with https://github.com/karen-irc/option-t/pull/337. We need to rethink it.

**Comment by saneyuki** [comment]
> If there are multiple versions of this package in user dependency tree, this change may reproduce the similar problem with #337 

This would be yes and it's worse to use `Symbol` as tagging like phantom type.

`Symbol` is always an unique value thus this breaks even if there is different minor/patch version. This is worse than using `string` as tagging (we can change `string` at an arbitrary).

**Comment by saneyuki** [comment]
After considerations, I feel that we should not resolve this problem by adding some tags to object type definition.

1. Fundamentally, we can sort the type which we illustrate in this motivation by adding a default type parameter.
2. By observations from some micro benchmarks, this would not improve a performance, but rather this would be worse for performance by changing hidden class (v8)/Structure (JSC)/Shape (SpiderMonkey).
    * If use the different symbol as the key of property, hidden class would be change. This might be a penalty.
    * Even if we pass objects having different hidden class (both `PlainResult<T, E>` and `PlainOption<T>`) to same function's arguments, I suspect it would not be a problem by working polymorphic inline cache nicely.
        * V8 7.5 creates a different hidden class by whether object's member is `number` or not. So `Some(string|object)` and `Some(number)` is different _hidden class_. But  JSC (for Safari 13) use same _structure_. Thus if we pass `PlainOption<T>` and `PlainResult<T, E>` to a `function bar(a)` as argument _a_, the type of _a_ would be 2~4. This number would work nicely with PIC. 
3. Tagging would be safe for the future breaking change, but then we need extra checking to make all operators works with compatible. And I doubt we need to change the type of `PlainOption` and `PlainResult` for the future. They are simple and work. If we need to do it, it would be a best way to rename them.

**Comment by saneyuki** [comment]
> Fundamentally, we can sort the type which we illustrate in this motivation by adding a default type parameter.

It's nice to add default type parameter after we finish #345.
But then TypeScript will be post-3.5, `unknown ` will be use for it. then we might not think this as a problem....

**Comment by tetsuharuohzeki** [comment]
We lives in the era after typescript 3.5. I think this would not be a problem.
